#!/bin/zsh

echo "Running Brew..."

# setup nix
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

# Update brew packages
brew bundle --file=Brewfile

echo "Running stow to update symlinks..."

# Symlink dotfiles using stow
stow .

# Stow packages that target ~ instead of ~/.config
stow --target="$HOME" zsh
stow --target="$HOME" oh-my-zsh
stow --target="$HOME" git

echo "Done!"
